// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package override

import (
	"github.com/crater-io/sqlc-testdata/pkg"
)

type Foo struct {
	Other   string
	Total   int64
	Retyped pkg.CustomType
}
